---

- hosts: all # playbook will be running on all hosts listed in inventory file
  become: true # run with sudo, ask for sudo password during run
  tasks:

  - name: install apache2 and php
    package: # linux-independent keyword for the package manager (pl. apt)
      name:
        - " {{ apache_package }}" # variable which is defined in the inventory file
        - " {{ php_package }} " # variable which is defined in the inventory file
      state: latest
      update_cache: yes

